apiVersion: ccm.harness.io/v1
kind: AutoStoppingRule
metadata:
    name: autostopping-sample
    namespace: default
    annotations:
        harness.io/cloud-connector-id: autostopautopilot_Costaccess
spec:
    service:
        name: autostopping-sample
        port: 80
    ingress:
        name: autostopping-sample
        controllerName: nginx
    idleTimeMins: 5
    hideProgressPage: false
